### ISSUE TITLE
Project name clash

### ISSUE THREAD

**Issue by duck-rh** [joonatoona/OpenShift#1]
When you create a new project, if you want to have visibility and avoid trademark issues, then you'd better check if the name is already used.

Please see https://en.wikipedia.org/wiki/OpenShift

**Comment by smichel17** [comment]
@duck-rh I understand that the US trademark system sucks and it can be "prosecute now or lose your right to do so later", but you don't have to hang an implicit threat of prosecution over people's heads. Or at least, not until after you've asked nicely.

@joonatoona Overall, I don't think Red Hat would have a good legal case, but unless you're really attached to this name, it would be polite to rename the project, to LibreShift, for example.

---

Red Hat has two trademarks on "OpenShift", both "for deploying, scaling, monitoring and managing web sites, web services, mobile application services, datastores and messaging interconnects."

1. "Computer software" [(source)](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4801:nygkk9.3.1)
2. "Platform as a service (PAAS) featuring computer software platforms" [(source)](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4801:nygkk9.3.3)

Considering that this app is self-described as "Open source root mode Android color adjusting," I don't think Red Hat has a very good case for infringement, and even if they won, I think they'd be hard pressed to get anything more than compelling this project to change its name.

There might be a better case for brand dilution, but this project is noncommercial, so that's another hard case. A lot would ride on how much brand recognition Red Hat's OpenShift has.

Of course, being taken to court is a pain, win or lose.

---
Obligatory: I am not a lawyer and the above is not legal advice.

**Comment by joonatoona** [comment]
I did do some research, clearly not enough though because I didn't see that.

Thanks for all the info @smichel17 , I will start renaming to LibreShift now.

**Comment by joonatoona** [comment]
Fixed in [release](https://github.com/joonatoona/OpenShift/releases/tag/v0.2-alpha). I belive internal naming isn't subject to trademarks, but I am not a lawyer and have no clue what I'm talking about.

**Comment by duck-rh** [comment]
It was not a legal threat in any way. i stumbled onto it while looking at new apps on F-Droid and thought "ho nice, someone made an app for OpenShift", and obviously you understand my disappointment.
So I don't think Red Hat is going to do anything, but this project is never gonna be found by people on search engines with the original name.

Btw I'd be curious to know how you got from this app topic to this name.

**Comment by joonatoona** [comment]
I apologize for any confusion, I got this name because I needed to name the repo for dumping all my stuff.

Its open, and it shifts the colors on screen.

**Comment by duck-rh** [comment]
Since I did not try it I did not get it. Thanks :-)
